### ISSUE TITLE
Blockquote

### ISSUE THREAD

**Issue by peterwilsoncc** [peterwilsoncc/joy949-patterns#10]
This is from the post-single selector, which seems most likely candidate for the bog standard blockquote.

```css
.post-single blockquote {
  border-left: solid 3px #ececec;
  color: #999;
  margin: 10px;
  padding: 0 15px;
}
```
